"""Aim to distribute and install Python package of the rag system."""
import io
import os

from setuptools import find_packages, setup

# Metadata of package
NAME = 'RAG_seven_wonders'
DESCRIPTION = 'AI RAG Q&A system about the seven ancient wonders.'
URL = 'https://github.com/vladimirkanchev/haystack-train-rag/'
AUTHOR = 'Vladimir Kanchev'
EMAIL = 'kanchev.vladimir@gmail.com'
REQUIRES_PYTHON = '>=3.10'

pwd = os.path.abspath(os.path.dirname(__file__))


def list_reqs(fname='requirements.txt'):
    """List packages to be installed."""
    with io.open(os.path.join(pwd, fname), encoding='utf-8') as f:
        return f.read().splitlines()


with open('VERSION', encoding="utf-8") as version_file:
    _version = version_file.read().strip()

try:
    with io.open(os.path.join(pwd, 'README.md'), encoding='utf-8') as file:
        LONG_DESCRIPTION = '\n' + file.read()
except FileNotFoundError:
    LONG_DESCRIPTION = DESCRIPTION

setup(
    name=NAME,
    version=_version,
    description=DESCRIPTION,
    long_description=LONG_DESCRIPTION,
    long_description_content_type='text/markdown',
    author=AUTHOR,
    author_email=EMAIL,
    python_requires=REQUIRES_PYTHON,
    url=URL,
    include_package_data=True,
    packages=find_packages(),
    package_data={
        'rag_system': ['config.yml'],
    },
    install_requires=[
        'accelerate',
        'aiohappyeyeballs',
        'aiohttp',
        'aioredis',
        'aiosignal',
        'alembic',
        'altair',
        'aniso8601',
        'anyio',
        'appdirs',
        'argon2-cffi',
        'argon2-cffi-bindings',
        'astroid',
        'async-timeout',
        'attrs',
        'Authlib',
        'azure-ai-formrecognizer',
        'azure-common',
        'azure-core',
        'azure-storage-blob',
        'backoff',
        'beautifulsoup4',
        'blinker',
        'boilerpy3',
        'boto3',
        'botocore',
        'cachetools',
        'cattrs',
        'certifi',
        'cffi',
        'charset-normalizer',
        'click',
        'cloudpickle',
        'colorama',
        'coloredlogs',
        'construct',
        'contourpy',
        'cryptography',
        'cycler',
        'Cython',
        'databricks-sdk',
        'datasets',
        'Deprecated',
        'dill',
        'distro',
        'dnspython',
        'docker',
        'docopt',
        'elastic-transport',
        'elasticsearch',
        'email_validator',
        'entrypoints',
        'environs',
        'Events',
        'exceptiongroup',
        'faiss-cpu==1.8.0.post1',
        'fastapi',
        'fastapi-cache',
        'fastapi-cli',
        'fastjsonschema',
        'filelock',
        'Flask',
        'flatbuffers',
        'fonttools',
        'frozenlist',
        'fsspec',
        'gitdb',
        'GitPython',
        'google-auth',
        'graphene',
        'graphql-core',
        'graphql-relay',
        'greenlet',
        'grpcio',
        'gunicorn',
        'h11',
        'haystack-ai',
        'haystack-bm25',
        'haystack-experimental',
        'hiredis',
        'httpcore',
        'httptools',
        'httpx',
        'huggingface-hub',
        'humanfriendly',
        'idna',
        'importlib_metadata',
        'inflect',
        'isodate',
        'isort',
        'itsdangerous',
        'jarowinkler',
        'Jinja2',
        'jmespath',
        'joblib',
        'jsonschema',
        'jsonschema-specifications',
        'jupyter_core',
        'kiwisolver',
        'langdetect',
        'lazy-imports',
        'llvmlite',
        'loguru',
        'lxml',
        'Mako',
        'Markdown',
        'markdown-it-py',
        'MarkupSafe',
        'marshmallow',
        'matplotlib',
        'mccabe',
        'mdurl',
        'milvus-haystack',
        'milvus-lite',
        'milvus-model',
        'minio',
        'mlflow',
        'mlflow-skinny',
        'monotonic',
        'more-itertools',
        'mpmath',
        'msgpack',
        'msrest',
        'multidict',
        'multiprocess',
        'nbformat',
        'networkx',
        'nltk',
        'num2words',
        'numba',
        'numpy',
        'oauthlib',
        'onnxruntime',
        'openai',
        'openai-whisper',
        'opensearch-py',
        'opentelemetry-api',
        'opentelemetry-sdk',
        'opentelemetry-semantic-conventions==0.47b0',
        'outcome==1.3.0.post0',
        'packaging',
        'pandas',
        'pdf2image',
        'pefile',
        'pigar',
        'pillow',
        'pinecone-client',
        'platformdirs',
        'posthog',
        'prompthub-py',
        'protobuf',
        'psutil',
        'psycopg2-binary',
        'pyarrow',
        'pyarrow-hotfix',
        'pyasn1',
        'pyasn1_modules',
        'pycodestyle',
        'pycparser',
        'pycryptodome',
        'pydantic',
        'pydeck',
        'pydocstyle',
        'pyflakes',
        'Pygments',
        'pylama',
        'pylint',
        'pymilvus',
        'pymongo',
        'pyparsing',
        'PySocks',
        'pytesseract',
        'python-box',
        'python-dateutil==2.9.0.post0',
        'python-docx',
        'python-dotenv',
        'python-frontmatter',
        'python-magic',
        'python-multipart',
        'python-pptx',
        'python-ptrace',
        'pytz',
        'PyYAML',
        'quantulum3',
        'querystring-parser',
        'rank-bm25',
        'rapidfuzz',
        'referencing',
        'regex',
        'requests',
        'requests-cache',
        'requests-oauthlib',
        'rich',
        'rpds-py',
        'rsa',
        'ruamel.yaml',
        'ruamel.yaml.clib',
        's3transfer',
        'safetensors',
        'scikit-learn',
        'scipy',
        'selenium',
        'sentence-transformers',
        'sentencepiece',
        'seqeval',
        'shellingham',
        'six',
        'smmap',
        'sniffio',
        'snowballstemmer',
        'sortedcontainers',
        'soupsieve',
        'SQLAlchemy',
        'SQLAlchemy-Utils',
        'sqlparse',
        'sseclient-py',
        'starlette',
        'streamlit',
        'sympy',
        'tenacity',
        'threadpoolctl',
        'tika',
        'tiktoken',
        'tokenizers',
        'toml',
        'tomli',
        'tomlkit',
        'toolz',
        'torch==2.1.0+cpu',
        'torchaudio==2.1.0+cpu',
        'torchvision==0.16.0+cpu',
        'tornado',
        'tqdm',
        'traitlets',
        'transformers',
        'trio',
        'trio-websocket',
        'triton',
        'typeguard',
        'typer',
        'typing_extensions',
        'tzdata',
        'ujson',
        'url-normalize',
        'urllib3',
        'uvicorn',
        'uvloop',
        'validators',
        'watchdog',
        'watchfiles',
        'weaviate-client',
        'websocket-client',
        'websockets',
        'Werkzeug',
        'wrapt',
        'wsproto',
        'XlsxWriter',
        'xxhash',
        'yarl',
        'zipp',
    ],
    extras_require={},
    license='Apache License Version 2.0',
    classifiers=[
        'Programming language :: Python :: 3',
        'Programming language :: Python :: 3.10',
        'License :: OSI Aproved :: Apache License Version 2.0',
        'Operating System :: OS I'
    ],
    entry_points={
        'console_scripts': [
            'start-rag-system=fastapi_aws_deploy:run',  # Entry point
            'start-streamlit-app=run_app_streamlit:main'
        ]
    },
)
